### ISSUE TITLE
Aerospike EE support

### ISSUE THREAD

**Issue by rakeshfromflipkart** [G-Research/vault-plugin-database-aerospike#15]
Would this plugin work for Aerospike EE same as community version ?

**Comment by jgiannuzzi** [comment]
Hi @rakeshfromflipkart, this plugin actually _only_ works with Aerospike EE, as it requires the [Access Control](https://docs.aerospike.com/server/guide/security/access-control) feature.

**Comment by rakeshfromflipkart** [comment]
Hi @jgiannuzzi , thanks for the update. 

Had this question since I'm unable to connect to Aerospike EE server.

when I run the command 

`vault write database/config/aerospike plugin_name=aerospike-database-plugin allowed_roles="*" host='http://localhost:3000' username='admin' password='admin123'`


`Error writing data to database/config/aerospike: Error making API request.

URL: PUT http://127.0.0.1:8200/v1/database/config/aerospike
Code: 400. Errors:

* error creating database object: invalid database version: 2 errors occurred:
	* Unrecognized remote plugin message:

This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol.
	* Unrecognized remote plugin message:`
	
	
	Any idea what might be causing this ?

**Comment by rakeshfromflipkart** [comment]
```
# aql --version
Aerospike Query Client
Version 6.1.0
C Client Version 5.2.3
```

```
vault status
Key             Value
---             -----
Seal Type       shamir
Initialized     true
Sealed          false
Total Shares    1
Threshold       1
Version         1.8.4
Storage Type    file
Cluster Name    vault-cluster-824986c7
Cluster ID      8abfd085-a45a-d6e4-418d-8eb8abc9a638
HA Enabled      false
```

**Comment by rakeshfromflipkart** [comment]
Thanks for the update @jgiannuzzi .

Had this question since I am not able to connect to Aerospike EE server, might be a connection issue from my end.
